### ISSUE TITLE
can’t get start

### ISSUE THREAD

**Issue by w827** [teacat/chaturbate-dvr#28] opened 2023-03-13 18:06 UTC
always
2023/03/13 18:02:49 [INFO] emilybatee is not online, check again in 1 minute(s)

--v0.93-alpha

**Comment by YamiOdymel** [comment] 2023-03-13 20:05
Seems working to me, can't reproduce the issue 🤔

```
2023/03/14 04:04:15 [RECORDING] emilybatee is online! start fetching..
2023/03/14 04:04:16 the video will be saved as "./video/emilybatee_2023-03-14_04-04-15.ts".
2023/03/14 04:04:19 fetching media_w1781649554_b5128000_t64RlBTOjMwLjA=_10360.ts (size: 1015200)
2023/03/14 04:04:19 fetching media_w1781649554_b5128000_t64RlBTOjMwLjA=_10359.ts (size: 1057124)
2023/03/14 04:04:19 fetching media_w1781649554_b5128000_t64RlBTOjMwLjA=_10361.ts (size: 1062576)
2023/03/14 04:04:20 [INFO] inserting 1 segment to the master file. [total: 4]
2023/03/14 04:04:21 [INFO] inserting 2 segment to the master file. [total: 4]
2023/03/14 04:04:21 [INFO] inserting 3 segment to the master file. [total: 6]
2023/03/14 04:04:21 fetching media_w1781649554_b5128000_t64RlBTOjMwLjA=_10362.ts (size: 984932)
2023/03/14 04:04:21 [INFO] inserting 4 segment to the master file. [total: 6]
```

**Comment by YamiOdymel** [comment] 2023-03-15 16:01
I tried it again today and it's still working, are you both fine with browsing Chaturbate with browser?

Can you go to a streaming channel and press `F12` > `Network Tab` and search for `.m3u8` see if the `Status Code` is `200` ?

![image](https://user-images.githubusercontent.com/7308718/225368236-fb87b8e0-3c8e-471e-8154-fd7084f3780b.png)

**Comment by YamiOdymel** [comment] 2023-03-15 16:21
Was it working normally before? Or you are new to use the program? 🤔

**Comment by YamiOdymel** [comment] 2023-03-15 16:33
Oh- no-, That error message is a big hint.

That's not a bug but **Chaturbate** sometimes **randomly blocking** viewers from fetching thier stream playlist, maybe unstable network of their server. 

There's no way to fixed it, you can only wait for it to be fixed by itself.

(if there's another solution please link it back and let me know 🥺)


Related:
* https://github.com/ytdl-org/youtube-dl/issues/23257
* https://github.com/streamlink/streamlink/issues/2056
* https://github.com/teacat/chaturbate-dvr/issues/20

**Comment by pimodege** [comment] 2023-03-15 17:42
This does seem to be caused by Cloudflare, rather than an issue with your program. Many thanks.

**Closed** 2023-03-15 19:30 UTC
